config_version: 0.0.1
model_variants:
  s2_fos_0_0_1: 
    # Class path to pydantic Instance implementation in <model_package_name>==<model_package_version>
    instance: tt.interface.Instance

    # Class path to pydantic Prediction implementation in <model_package_name>==<model_package_version>
    prediction: tt.interface.Prediction

    # Class path to Predictor implementation in <model_package_name>==<model_package_version>
    predictor: tt.interface.Predictor

    # Class path to pydantic PredictorConfig implementation in <model_package_name>==<model_package_version>
    predictor_config: tt.interface.PredictorConfig

    # Any additional sets of dependencies required by the model.
    # These are the 'extras_require' keys in your setup.py.
    extras_require: []

    # Full S3 path to tar.gz'ed artifacts archive, nullable
    artifacts_s3_path: s3://ai2-s2-research/fos/packaged_artifacts/artifacts.tar.gz

    # Version of python required for model runtime, e.g. 3.7, 3.8, 3.9
    python_version: 3.8

    # Whether this model supports CUDA GPU acceleration
    cuda: False

    # Python path to a fn in <model_package_name>==<model_package_version> that
    # returns a unittest.TestCase. Builder function receives a model container
    # as its sole argument.
    # Used by the TIMO toolchain to validate your model implementation and configuration.
    integration_test: tt.integration_test.TestInterfaceIntegration

    # One or more bash commands to execute as part of a RUN step in a Dockerfile.
    # Leave this unset unless your model has special system requirements beyond
    # those in your setup.py.
    docker_run_commands: []

