LABELS = [
    'Agricultural and Food Sciences',
    'Art',
    'Biology',
    'Business',
    'Chemistry',
    'Computer Science',
    'Economics',
    'Education',
    'Engineering',
    'Environmental Science',
    'Geography',
    'Geology',
    'History',
    'Law',
    'Linguistics',
    'Materials Science',
    'Mathematics',
    'Medicine',
    'Philosophy',
    'Physics',
    'Political Science',
    'Psychology',
    'Sociology']